# Configuration pour GitHub Pages
title: Smart Hotline Agency
description: Services de communication téléphonique pour PME
baseurl: ""
url: "https://votrenomdutilisateur.github.io"

# Build settings
markdown: kramdown
highlighter: rouge
plugins:
  - jekyll-feed

# Exclude from processing
exclude:
  - Gemfile
  - Gemfile.lock
  - node_modules
  - vendor/bundle/
  - vendor/cache/
  - vendor/gems/
  - vendor/ruby/
  - en/
  - assets/
  - images/
  - _config.yml
  - README.md

# Include directories
include:
  - _redirects
