[build]
  publish = "."

# Redirect from index-fr.html to index.html
[[redirects]]
  from = "/fr/index-fr.html"
  to = "/fr/index.html"
  status = 301

# Language-based redirects
[[redirects]]
  from = "/"
  to = "/fr/index.html"
  status = 302

# Remove _new from URLs
[[redirects]]
  from = "/*"
  to = "/:splat"
  status = 301
  conditions = {query = {"_new": "true"}}
