[build]
  # Supprime les scripts de build inutiles
  publish = "."  # Le dossier racine est le dossier de publication

# Note: Toutes les redirections (redirects) sont déplacées dans le fichier _redirects
# Netlify.toml n'est pas l'endroit idéal pour les redirects complexes.
